name: Publish Package to npmjs
on:
  workflow_run:
    workflows:
      - 'Run Tests'
    branches: ["canary", "*.x"]
    types:
      - completed
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 10

      - name: Use Node.js 22.x
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: NPM Audit
        run: pnpx audit-ci

      - name: Install Node Modules
        run: pnpm i

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpx semantic-release
