name: Run Tests
on:
  pull_request:
    branches:
      - canary
      - "*.x"
      - 'main'
  push:
    branches:
      - canary
      - "*.x"
      - main
permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x, 24.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: NPM Audit
        run: pnpx audit-ci

      - name: Install Node Modules
        run: pnpm i

      - name: Run Checks
        run: pnpm run check

      - uses: actions/upload-artifact@v7
        with:
          name: test-reports-${{ matrix.node-version }}
          path: test/reports/
